app:
    topnav:
        Home: {link: ''}
        Contact: {link: contact}
        About: {link: about}
        Admin: {link: drafts, requireLogin: true}
    topnav_disabled:
        Articles: articles
        Software: software
        Links: links
        Blog: blog
zinc:
    gui:
        default:
            driver: smarty2
